Repository openshift/cloud-credential-operator, pull requests merged in 2019-07, with the labels that each got.

#78 fix cloud name typo
  pkg/aws/actuator/actuator.go
Labels: approved, lgtm, size/XS

#81 Bug 1726451: Add clusteroperator version level gate.
  manifests/10_cluster-operator.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#83 Introduce gocheck for security checks
  Makefile
Labels: approved, lgtm, size/XS

#82 Enable leader election.
  cmd/manager/main.go
  config/kustomization.yaml
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
  manifests/01_deployment.yaml
  pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/status.go
Labels: approved, lgtm, size/L

#79 ignore credentialsRequests for other clouds
  pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  pkg/controller/controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/credentialsrequest/status.go
  pkg/controller/credentialsrequest/status_test.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/L

#86 implement GCP passthrough mode (and add service API checks)
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/controller/utils/gcp/utils.go
  pkg/controller/utils/gcp/utils_test.go
  pkg/gcp/actuator/actuator.go
  pkg/gcp/actuator/policy.go
  pkg/gcp/actuator/role.go
  pkg/gcp/actuator/utils.go
Labels: approved, lgtm, size/XL

#90 Revert "Bug 1726451: Add clusteroperator version level gate."
  manifests/10_cluster-operator.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#88 Bug 1727012: add upgradeable condition unconditionally
  pkg/controller/credentialsrequest/status.go
  pkg/controller/credentialsrequest/status_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#92 gcp: match secret name/key to installer manifest
  pkg/controller/secretannotator/gcp/reconciler.go
  pkg/gcp/actuator/actuator.go
Labels: approved, lgtm, size/XS

#93 [gcp] Allow skipping service checks
  pkg/apis/cloudcredential/v1/gcp_types.go
  pkg/gcp/actuator/actuator.go
Labels: approved, lgtm, size/S

#94 Split call to check permissions into chunks
  pkg/controller/utils/gcp/utils.go
  pkg/controller/utils/gcp/utils_test.go
Labels: approved, lgtm, size/M

#89 Bug 1729021: utilize the permissionBoundary of the current user if available
  pkg/aws/actuator/actuator.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/M
