Repository openshift/cloud-credential-operator, pull requests merged in 2019-08, with the labels that each got.

#96 [gcp]: Fix project used by cloud credential operator
  Gopkg.lock
  pkg/aws/actuator/actuator.go
  pkg/controller/controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/controller/platform/platform.go
  pkg/controller/secretannotator/gcp/reconciler.go
  pkg/controller/secretannotator/gcp/reconciler_test.go
  pkg/controller/secretannotator/secretannotator_controller.go
  pkg/gcp/actuator/actuator.go
  pkg/gcp/client.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/authorization/v1/doc.go
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/console/v1/register.go
  vendor/github.com/openshift/api/console/v1/types_console_external_log_links.go
  vendor/github.com/openshift/api/console/v1/types_console_link.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/doc.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_scheduler.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/types.go
Labels: approved, lgtm, size/XXL

#97 4.2 Upgrade: Don't assume platformStatus is present in Infra
  pkg/controller/controller.go
  pkg/controller/platform/platform.go
  pkg/controller/secretannotator/secretannotator_controller.go
Labels: approved, lgtm, size/M

#98 Bug 1707827: Enable leader election.
  cmd/manager/main.go
  config/kustomization.yaml
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
  manifests/01_deployment.yaml
  pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/status.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#100 update docs to reflect that we are now at v1 (not v1beta1)
  README.md
Labels: approved, lgtm, size/XS

#103 Bug 1742753: clear other conditions when ignoring a cred request
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/credentialsrequest/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#105 Bug 1743728: pkg/azure: also provide operators access to the resource group containing public DNS zone
  manifests/01_deployment.yaml
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/azure/passthrough_test.go
  pkg/azure/resourceid.go
  pkg/azure/resourceid_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#106 status: Add CredentialsRequests to relatedObjects
  pkg/controller/credentialsrequest/status.go
Labels: approved, lgtm, size/S

#107 [gcp] set timeout on cloud API calls
  pkg/gcp/client.go
Labels: approved, lgtm, size/M

#104 tag Service Principals on create
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/azure/minter.go
  pkg/azure/passthrough_test.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/status_test.go
Labels: approved, lgtm, size/L

#108 allow 32 char infraID in generated Service Principal names
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
  pkg/gcp/actuator/actuator.go
  pkg/gcp/actuator/utils.go
Labels: approved, lgtm, size/L
