Repository openshift/cloud-credential-operator, pull requests merged in 2019-04, with the labels that each got.

#49 update docs on passthrough mode to more closely reflect reality
  README.md
Labels: approved, lgtm, size/XS

#50 Bug: 1695205 Reset progressing transition time after upgrades.
  pkg/controller/credentialsrequest/status.go
  pkg/controller/credentialsrequest/status_test.go
Labels: approved, lgtm, size/L

#52 Update tagging to match newest scheme via installer.
  pkg/aws/actuator/actuator.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/L

#53 Fix error on beta3 clusters with no infra name.
  pkg/aws/actuator/actuator.go
  pkg/aws/actuator/actuator_test.go
Labels: approved, lgtm, size/S

#54 Fix the hotloop on certain types of errors.
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
Labels: approved, lgtm, size/M

#55 Make AWSProviderCodec generic for other clouds
  pkg/apis/cloudcredential/v1/codec.go
  pkg/aws/actuator/actuator.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/M

#58 provide pod logs via API on failures
  manifests/0000_30_cloud-credential-operator_01_deployment.yaml
Labels: approved, lgtm, size/XS

#57 Azure Provider Passthrough Actuator
  pkg/apis/cloudcredential/v1/azure_types.go
  pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/azure/base.go
  pkg/azure/client.go
  pkg/azure/passthrough.go
  pkg/azure/passthrough_test.go
  pkg/azure/request.go
  pkg/azure/secret.go
  pkg/controller/controller.go
  pkg/controller/secretannotator/secretannotator_controller.go
Labels: approved, lgtm, size/XL

#59 add cluster-reader role to aggregate
  manifests/0000_30_cloud-credential-operator_00_clusterreader_clusterrole.yaml
Labels: approved, lgtm, size/S

#60 move to reporting the new Degraded state for the clusteroperator object
  Gopkg.lock
  config/manager/deployment.yaml
  manifests/0000_30_cloud-credential-operator_01_deployment.yaml
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/credentialsrequest/status.go
  pkg/controller/credentialsrequest/status_test.go
  pkg/util/clusteroperator/status_test.go
  vendor/github.com/openshift/api/.travis.yml
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/apps/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/legacyconfig/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_scheduler.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/webconsole/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XL

#61 Add node-selector annotation to namespace
  config/manager/deployment.yaml
  manifests/0000_30_cloud-credential-operator_01_deployment.yaml
Labels: approved, lgtm, size/XS

#62 Move component to an appropriate upgrade order (generic)
  manifests/00_clusterreader_clusterrole.yaml
  manifests/00_v1_crd.yaml
  manifests/01_deployment.yaml
  manifests/03_cred-iam-ro.yaml
  manifests/10_cluster-operator.yaml
Labels: approved, lgtm, size/XS
