Repository openshift/cloud-credential-operator, pull requests merged in 2019-02, with the labels that each got.

#27 Fix OOM by increasing memory limits for controller.
  config/manager/deployment.yaml
  pkg/controller/controller.go
Labels: approved, lgtm, size/XS

#28 Update README with some high level notes on the project.
  README.md
Labels: approved, lgtm, size/S

#30 document scaling down in-cluster bits
  README.md
Labels: approved, lgtm, size/XS

#31 Deploy before runlevel 30 so machine API can get creds.
  Makefile
  manifests/0000_30_cloud-credential-operator_00_crd.yaml
  manifests/0000_30_cloud-credential-operator_01_deployment.yaml
  manifests/0000_30_cloud-credential-operator_03_cred-iam-ro.yaml
  manifests/0000_30_cloud-credential-operator_03_cred-openshift-cluster-api.yaml
  manifests/0000_30_cloud-credential-operator_03_cred-openshift-image-.txt
  manifests/0000_30_cloud-credential-operator_03_cred-openshift-image-registry.yaml
  manifests/0000_30_cloud-credential-operator_03_cred-openshift-image.txt
  manifests/0000_30_cloud-credential-operator_03_cred-openshift-ingress.yaml
Labels: approved, lgtm, size/S

#13 Publish a ClusterOperator with conditions for status
  Dockerfile
  config/manager/deployment.yaml
  config/rbac/rbac_role.yaml
  manifests/0000_30_cloud-credential-operator_01_deployment.yaml
  manifests/0000_30_cloud-credential-operator_03_cred-openshift-image-.txt
  manifests/0000_30_cloud-credential-operator_03_cred-openshift-image.txt
  manifests/0000_30_cloud-credential-operator_03_cred-openshift-machine-api.yaml
  manifests/10-cluster-operator.yaml
  pkg/apis/cloudcredential/v1beta1/credentialsrequest_types.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/credentialsrequest/status.go
  pkg/controller/credentialsrequest/status_test.go
  pkg/controller/utils/condition_utils.go
  pkg/util/clusteroperator/status.go
  pkg/util/clusteroperator/status_test.go
  version/version.go
Labels: approved, lgtm, size/XL

#32 refactor credentialsrequest controller
  config/crds/cloudcredential_v1beta1_credentialsrequest.yaml
  manifests/0000_30_cloud-credential-operator_00_crd.yaml
  pkg/apis/cloudcredential/v1beta1/credentialsrequest_types.go
  pkg/aws/actuator/actuator.go
  pkg/controller/credentialsrequest/actuator/actuator.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/L

#36 pkg/controller/utils: Fix "reutrn" -> "return" comment typo
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/XS
