Repository openshift/cloud-credential-operator, pull requests merged in 2019-01, with the labels that each got.

#4 Remove unnecessary deps from build image.
  build/build-image/Dockerfile
Labels: size/S

#5 Add build/test make targets that do not require generation.
  Makefile
Labels: size/XS

#3 Store user policy name in AWS status.
  pkg/apis/cloudcredential/v1beta1/aws_types.go
  pkg/aws/actuator/actuator.go
Labels: lgtm, size/M

#7 Add OWNERS for /approve.
  OWNERS
Labels: size/XS

#10 Drop unused go get in Dockerfile.
  Dockerfile
Labels: approved, lgtm, size/XS

#12 validating cloud creds
  Gopkg.lock
  Gopkg.toml
  Makefile
  config/rbac/rbac_role.yaml
  hack/update-bindata.sh
  pkg/aws/actuator/actuator.go
  pkg/aws/client.go
  pkg/aws/mock/client_generated.go
  pkg/controller/add_secretannotator.go
  pkg/controller/assets/bindata.go
  pkg/controller/credentialsrequest/actuator/actuator.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/secretannotator/secretannotator_controller.go
  pkg/controller/secretannotator/secretannotator_controller_test.go
  pkg/controller/utils/utils.go
  vendor/github.com/jteeuwen/go-bindata/CONTRIBUTING.md
  vendor/github.com/jteeuwen/go-bindata/LICENSE
  vendor/github.com/jteeuwen/go-bindata/README.md
  vendor/github.com/jteeuwen/go-bindata/asset.go
  vendor/github.com/jteeuwen/go-bindata/bytewriter.go
  vendor/github.com/jteeuwen/go-bindata/config.go
  vendor/github.com/jteeuwen/go-bindata/convert.go
  vendor/github.com/jteeuwen/go-bindata/debug.go
  vendor/github.com/jteeuwen/go-bindata/doc.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/main.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/version.go
  vendor/github.com/jteeuwen/go-bindata/release.go
  vendor/github.com/jteeuwen/go-bindata/stringwriter.go
  vendor/github.com/jteeuwen/go-bindata/testdata/in/a/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/in/b/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/in/c/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/in/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/out/compress-memcopy.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/compress-nomemcopy.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/debug.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/nocompress-memcopy.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/nocompress-nomemcopy.go
  vendor/github.com/jteeuwen/go-bindata/toc.go
Labels: approved, lgtm, size/XXL

#11 Integrate into release image
  Dockerfile
  Makefile
  README.md
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/manager/deployment.yaml
  config/rbac/rbac_role.yaml
  manifests/00-cloudcredential-crd.yaml
  manifests/01-deployment.yaml
  manifests/03-cred-iam-ro.yaml
  manifests/03-cred-openshift-image-registry.yaml
  manifests/03-cred-openshift-ingress.yaml
  manifests/image-references
  pkg/aws/actuator/actuator.go
  pkg/controller/assets/bindata.go
  pkg/controller/controller.go
  pkg/controller/credentialsrequest/actuator/actuator.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
Labels: approved, lgtm, size/XL

#14 Add additional S3 permissions for the Image Registry Operator
  manifests/03-cred-openshift-image-registry.yaml
Labels: approved, lgtm, size/XS

#17 Custom RateLimiter for CredentialsRequest controller
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/internalcontroller/controller.go
Labels: approved, lgtm, size/L

#19 adding permissions to upload/download objects
  manifests/03-cred-openshift-image-registry.yaml
Labels: approved, lgtm, size/XS

#20 Complete support for adding install config user tags to users in AWS.
  pkg/aws/actuator/actuator.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
Labels: approved, lgtm, size/M

#21 Fix missing configmap permissions.
  config/rbac/rbac_role.yaml
  manifests/01-deployment.yaml
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
Labels: approved, lgtm, size/XS

#15 add conditions for credentials requests
  config/crds/cloudcredential_v1beta1_credentialsrequest.yaml
  manifests/00-cloudcredential-crd.yaml
  pkg/apis/cloudcredential/v1beta1/credentialsrequest_types.go
  pkg/apis/cloudcredential/v1beta1/zz_generated.deepcopy.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/utils/condition_utils.go
Labels: approved, lgtm, size/XL

#16 openshift-ingress: Change namespace and permissions
  manifests/03-cred-openshift-ingress.yaml
Labels: approved, lgtm, size/S

#26 Remove secret controller refs.
  pkg/aws/actuator/actuator.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
Labels: approved, lgtm, size/M

#25 allow passing in your own list of actions to perm-check against
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/XS
