Repository openshift/cloud-credential-operator, pull requests merged in 2019-12, with the labels that each got.

#143 Bug 1776394: fix up ServiceMonitor CR
  config/manager/servicemonitor.yaml
  manifests/05_deployment.yaml
  pkg/assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#144 Use `CloudCredentialOperator` as alert prefix for humans
  config/manager/prometheusrule.yaml
  manifests/05_deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/M

#145 Bug 1781798: Use `CloudCredentialOperator` as alert prefix for humans
  config/manager/prometheusrule.yaml
  manifests/05_deployment.yaml
  pkg/assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#146 Bug 1781109: pre-populate conditions with count of zero
  pkg/controller/credentialsrequest/constants/constants.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/credentialsrequest/status.go
  pkg/controller/metrics/metrics.go
  pkg/controller/metrics/metrics_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#148 consistently use Fatal() logging for early exit
  cmd/manager/main.go
Labels: approved, lgtm, size/S
