Repository openshift/cloud-credential-operator, pull requests merged in 2019-03, with the labels that each got.

#34 aws: include operator version in UserAgent for AWS API calls
  pkg/aws/client.go
Labels: approved, lgtm, size/XS

#35 Remove limits from pods
  config/manager/deployment.yaml
  manifests/0000_30_cloud-credential-operator_01_deployment.yaml
Labels: approved, lgtm, size/XS

#37 Remove Machine API manifest
  manifests/0000_30_cloud-credential-operator_03_cred-openshift-machine-api.yaml
Labels: approved, lgtm, size/M

#38 Use PullPolicy IfNotPresent instead of Always.
  Makefile
  config/default/manager_image_patch.yaml
  config/kustomization.yaml
  config/manager/deployment.yaml
  manifests/0000_30_cloud-credential-operator_01_deployment.yaml
Labels: approved, lgtm, size/M

#39 Migrate CredentialsRequest from v1beta1 to v1.
  Makefile
  config/crds/cloudcredential_v1_credentialsrequest.yaml
  manifests/0000_30_cloud-credential-operator_00_v1_crd.yaml
  pkg/apis/addtoscheme_cloudcreds_v1.go
  pkg/apis/cloudcredential/v1/aws_types.go
  pkg/apis/cloudcredential/v1/codec.go
  pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  pkg/apis/cloudcredential/v1/doc.go
  pkg/apis/cloudcredential/v1/register.go
  pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  pkg/aws/actuator/actuator.go
  pkg/controller/credentialsrequest/actuator/actuator.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/credentialsrequest/status.go
  pkg/controller/credentialsrequest/status_test.go
  pkg/controller/utils/condition_utils.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/XXL

#40 Move cluster-operator definition to runlevel 30.
  manifests/0000_30_cloud-credential-operator_10_cluster-operator.yaml
Labels: approved, lgtm, size/XS

#41 Add docs on adding a new cloud provider actuator.
  README.md
Labels: approved, lgtm, size/S

#43 detect using root user
  pkg/controller/secretannotator/secretannotator_controller_test.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/M

#45 migrate the RO credentialsrequest from v1beta1 to v1
  manifests/0000_30_cloud-credential-operator_03_cred-iam-ro.yaml
Labels: approved, lgtm, size/XS

#44 resync credentialsrequests hourly
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
Labels: approved, lgtm, size/M

#46 remove v1beta1 cloudcredentials objects
  Makefile
  config/crds/cloudcredential_v1beta1_credentialsrequest.yaml
  manifests/0000_30_cloud-credential-operator_00_v1_crd.yaml
  pkg/apis/addtoscheme_cloudcreds_v1beta1.go
  pkg/apis/cloudcredential/v1beta1/aws_types.go
  pkg/apis/cloudcredential/v1beta1/codec.go
  pkg/apis/cloudcredential/v1beta1/credentialsrequest_types.go
  pkg/apis/cloudcredential/v1beta1/doc.go
  pkg/apis/cloudcredential/v1beta1/register.go
  pkg/apis/cloudcredential/v1beta1/zz_generated.deepcopy.go
  pkg/aws/actuator/actuator.go
  pkg/controller/credentialsrequest/actuator/actuator.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
Labels: approved, lgtm, size/XL

#47 Bug 1689442: Rename ClusterOperator to cloud-credential.
  manifests/0000_30_cloud-credential-operator_10_cluster-operator.yaml
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/credentialsrequest/status.go
  pkg/controller/credentialsrequest/status_test.go
Labels: approved, lgtm, size/XS

#48 Remove hardcoded amd64 for multi-arch
  Dockerfile
Labels: approved, lgtm, size/XS
