Repository openshift/cloud-credential-operator, pull requests merged in 2019-11, with the labels that each got.

#135 Add manifest annotations for hosted deployment exclusions
  manifests/05_deployment.yaml
  manifests/07_cred-iam-ro.yaml
  manifests/10_cluster-operator.yaml
Labels: approved, lgtm, size/XS

#136 add namespace to config/manager/
  Makefile
  config/manager/namespace.yaml
  config/rbac/prometheus_role.yaml
  manifests/05_deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/M

#140 Bug 1776704: change prometheus from summary to message
  config/manager/prometheusrule.yaml
  manifests/05_deployment.yaml
  pkg/assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#137 Bug 1776079: Azure: check existing role assignments before creating a new one
  pkg/azure/actuator_test.go
  pkg/azure/minter.go
  pkg/azure/passthrough_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#141 enable azure passthrough
  Gopkg.lock
  Gopkg.toml
  pkg/controller/secretannotator/azure/adal.go
  pkg/controller/secretannotator/azure/mock/adal_generated.go
  pkg/controller/secretannotator/azure/reconciler.go
  pkg/controller/secretannotator/azure/reconciler_test.go
Labels: approved, lgtm, size/L
