Repository openshift/cloud-credential-operator, pull requests merged in 2019-10, with the labels that each got.

#115 render manifests for use as a bootstrap pod
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/manager/main.go
  cmd/manager/render.go
  config/kustomization.yaml
  config/manager/deployment.yaml
  config/manager/namespace.yaml
  config/manager/service.yaml
  config/rbac/cloud-credential-operator_role.yaml
  config/rbac/cloud-credential-operator_role_binding.yaml
  hack/update-bindata.sh
  pkg/assets/bindata.go
  pkg/controller/configmap/configmap_controller.go
  pkg/controller/controller.go
  pkg/controller/platform/platform.go
  pkg/controller/secretannotator/secretannotator_controller.go
  vendor/github.com/jteeuwen/go-bindata/CONTRIBUTING.md
  vendor/github.com/jteeuwen/go-bindata/LICENSE
  vendor/github.com/jteeuwen/go-bindata/README.md
  vendor/github.com/jteeuwen/go-bindata/asset.go
  vendor/github.com/jteeuwen/go-bindata/bytewriter.go
  vendor/github.com/jteeuwen/go-bindata/config.go
  vendor/github.com/jteeuwen/go-bindata/convert.go
  vendor/github.com/jteeuwen/go-bindata/debug.go
  vendor/github.com/jteeuwen/go-bindata/doc.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/main.go
  vendor/github.com/jteeuwen/go-bindata/go-bindata/version.go
  vendor/github.com/jteeuwen/go-bindata/release.go
  vendor/github.com/jteeuwen/go-bindata/stringwriter.go
  vendor/github.com/jteeuwen/go-bindata/testdata/in/a/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/in/b/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/in/c/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/in/test.asset
  vendor/github.com/jteeuwen/go-bindata/testdata/out/compress-memcopy.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/compress-nomemcopy.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/debug.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/nocompress-memcopy.go
  vendor/github.com/jteeuwen/go-bindata/testdata/out/nocompress-nomemcopy.go
  vendor/github.com/jteeuwen/go-bindata/toc.go
Labels: approved, lgtm, size/XXL

#117 Bug 1758666: copy trust bundle when actually defined
  config/manager/deployment.yaml
  manifests/01_deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#119 Add support for manually disabling the operator.
  manifests/01_operator_configmap.yaml
  pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/credentialsrequest/status.go
  pkg/controller/credentialsrequest/status_test.go
  pkg/controller/secretannotator/aws/reconciler.go
  pkg/controller/secretannotator/aws/reconciler_test.go
  pkg/controller/secretannotator/azure/reconciler.go
  pkg/controller/secretannotator/gcp/reconciler.go
  pkg/controller/secretannotator/gcp/reconciler_test.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/L

#120 Annotate new configmap so CVO will allow changes.
  manifests/01_operator_configmap.yaml
Labels: approved, lgtm, size/XS

#123 commit changes to bindata
  pkg/assets/bindata.go
Labels: approved, lgtm, size/S

#125 initial scaffolding for CCO metrics
  cmd/manager/main.go
  pkg/controller/add_metrics.go
  pkg/controller/configmap/configmap_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/metrics/metrics.go
  pkg/controller/metrics/metrics_test.go
  pkg/controller/secretannotator/aws/reconciler.go
  pkg/controller/secretannotator/azure/reconciler.go
  pkg/controller/secretannotator/gcp/reconciler.go
Labels: approved, lgtm, size/L

#126 add metrics reporting the count of credReqs with conditions
  pkg/controller/metrics/metrics.go
  pkg/controller/metrics/metrics_test.go
Labels: approved, lgtm, size/M

#128 enable prometheus to scrape metrics
  config/kustomization.yaml
  config/manager/deployment.yaml
  config/manager/metrics-service.yaml
  config/manager/namespace.yaml
  config/manager/servicemonitor.yaml
  config/rbac/prometheus_role.yaml
  config/rbac/prometheus_role_binding.yaml
  manifests/01_deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/L

#129 add initial prometheus alerts
  config/kustomization.yaml
  config/manager/prometheusrule.yaml
  manifests/01_deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/L

#127 document metrics
  Documentation/metrics.md
Labels: approved, lgtm, size/M

#130 alert on insufficient cluster cloud creds
  config/manager/prometheusrule.yaml
  manifests/01_deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/M

#131 in the event that the secret for a CR is missing, re-reconcile
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
Labels: approved, lgtm, size/M

#133 Rough documentation for a disabled cred minter install
  Makefile
  config/kustomization.yaml
  docs/disabled-operator.md
  manifests/00_namespace.yaml
  manifests/05_deployment.yaml
  manifests/07_cred-iam-ro.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/L
