Repository openshift/cloud-credential-operator, pull requests merged in 2019-05, with the labels that each got.

#63 Populate all of the azure credential secret
  pkg/azure/passthrough.go
  pkg/azure/passthrough_test.go
  pkg/controller/secretannotator/secretannotator_controller.go
Labels: approved, lgtm, size/M

#65 Update cred namespace and secret name to match installer
  pkg/azure/client.go
Labels: approved, lgtm, size/XS

#66 Do not look for root creds during startup, instead validate for each request
  pkg/azure/actuator.go
  pkg/azure/client.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/status_test.go
Labels: approved, lgtm, size/M

#64 Fix tolerations
  config/manager/deployment.yaml
  manifests/01_deployment.yaml
Labels: approved, lgtm, size/S

#67 Azure secret annotator
  pkg/aws/actuator/actuator.go
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/azure/base.go
  pkg/azure/client.go
  pkg/azure/const.go
  pkg/azure/passthrough.go
  pkg/azure/passthrough_test.go
  pkg/azure/secret.go
  pkg/controller/controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/platform/platform.go
  pkg/controller/secretannotator/aws/reconciler.go
  pkg/controller/secretannotator/aws/reconciler_test.go
  pkg/controller/secretannotator/azure/reconciler.go
  pkg/controller/secretannotator/azure/reconciler_test.go
  pkg/controller/secretannotator/constants/const.go
  pkg/controller/secretannotator/secretannotator_controller.go
Labels: approved, lgtm, size/XL

#68 Drop memory limits on operator deployment.
  config/manager/deployment.yaml
Labels: approved, lgtm, size/XS
