Repository openshift/cloud-credential-operator, pull requests merged in 2019-06, with the labels that each got.

#70 Add OpenStack actuator
  pkg/apis/cloudcredential/v1/openstack_types.go
  pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  pkg/controller/controller.go
  pkg/openstack/actuator.go
Labels: approved, lgtm, size/L

#71 generate deployment and crd into the right filename
  .gitignore
  Makefile
  manifests/01_deployment.yaml
Labels: approved, lgtm, size/S

#75 Separate packages imported by installer from packages importing controller-runtime client
  pkg/aws/actuator/actuator.go
  pkg/aws/client.go
  pkg/aws/utils.go
  pkg/controller/secretannotator/aws/reconciler.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/XL

#76 Bug 1723892: Backport removal of memory restrictions for cred operator.
  .gitignore
  Makefile
  config/manager/deployment.yaml
  manifests/01_deployment.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S
