Repository openshift/cloud-credential-operator, pull requests merged in 2020-12, with the labels that each got.

#269 Bug 1898199: manifests: Allow 'for: 20m' for CloudCredentialOperatorDown
  manifests/05_deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#275 Bug 1903226: exclude run-level 0 namespaces from MutatingWebhook for Pods
  bindata/v4.1.0/aws-pod-identity-webhook/mutatingwebhook.yaml
  pkg/assets/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#278 Bug 1908747: remove stale S3 CredentialsRequest manifests
  manifests/05-s3-credentialsrequest.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm
