Repository openshift/cloud-credential-operator, pull requests merged in 2020-08, with the labels that each got.

#228 handle bootstrap user-defined mode
  Makefile
  bindata/bootstrap/cloudcredential_v1_credentialsrequest_crd.yaml
  bindata/bootstrap/cloudcredential_v1_operator_config_crd.yaml
  manifests/01-operator-config.yaml
  manifests/01-operator_configmap.yaml
  pkg/assets/bootstrap/bindata.go
  pkg/aws/actuator/actuator.go
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_vsphere_test.go
  pkg/operator/credentialsrequest/status_test.go
  pkg/operator/secretannotator/aws/reconciler_test.go
  pkg/operator/secretannotator/azure/reconciler_test.go
  pkg/operator/secretannotator/gcp/reconciler_test.go
  pkg/operator/secretannotator/vsphere/reconciler_test.go
  pkg/operator/utils/utils.go
Labels: approved, lgtm

#233 Bug 1868328: Fix cases in cloud-credential's related objects
  pkg/operator/awspodidentity/controller.go
  pkg/operator/credentialsrequest/status.go
  pkg/operator/secretannotator/status/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#235 Bug 1868328: CredentialsRequest should be plural
  pkg/operator/credentialsrequest/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#234 Bug 1871954: more auto deepcopy functions (less manual)
  pkg/apis/cloudcredential/v1/aws_manual.deepcopy.go
  pkg/apis/cloudcredential/v1/aws_manual.deepcopy_test.go
  pkg/apis/cloudcredential/v1/types_aws.go
  pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#239 Bug 1858403: Use client-go leader election to write less.
  go.mod
  pkg/cmd/operator/cmd.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
