Repository openshift/cloud-credential-operator, pull requests merged in 2020-03, with the labels that each got.

#158 provide region when setting up an AWS client
  pkg/aws/actuator/actuator.go
  pkg/aws/client.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
  pkg/controller/secretannotator/aws/reconciler.go
  pkg/controller/secretannotator/aws/reconciler_test.go
Labels: approved, lgtm, size/M

#159 Bug 1806892: no need to run CCO as privileged pod
  Dockerfile
  config/manager/namespace.yaml
  manifests/00_namespace.yaml
  pkg/assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#164 Bug 1794313: Some cluster operators fail to come up because RHV CA is not trusted by a pod
  pkg/ovirt/actuator.go
  pkg/ovirt/actuator_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#167 pkg/aws: allow users to create a client from IAM client
  pkg/aws/client.go
Labels: approved, lgtm

#166 Bug 1813343: handle old Infrastructure objects without PlatformStatus
  pkg/controller/utils/utils.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#163 search through source manifests to determine operator disabled
  cmd/manager/render.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/M

#171 add explicit --manifests-dir for render bootstrap
  cmd/manager/render.go
Labels: approved, lgtm
