Repository openshift/cloud-credential-operator, pull requests merged in 2020-01, with the labels that each got.

#149 docs: fix formatting
  docs/disabled-operator.md
Labels: approved, lgtm, size/S

#134 Add oVirt platform
  pkg/apis/cloudcredential/v1/ovirt_types.go
  pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  pkg/controller/controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/ovirt/actuator.go
  pkg/ovirt/actuator_test.go
Labels: approved, lgtm, size/XL

#152 Bug 1779390: force reconcile if any error conditions are set or !Provisioned
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#151 Fix exclusion annotation for hosted use case
  config/manager/deployment.yaml
  config/manager/prometheusrule.yaml
  config/rbac/prometheus_role.yaml
  manifests/05_deployment.yaml
  pkg/assets/bindata.go
Labels: approved, lgtm, size/S

#150 vSphere passthrough mode for CredentialsRequests
  pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  pkg/apis/cloudcredential/v1/vsphere_types.go
  pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  pkg/controller/controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller.go
  pkg/controller/credentialsrequest/credentialsrequest_controller_vsphere_test.go
  pkg/controller/secretannotator/secretannotator_controller.go
  pkg/controller/secretannotator/vsphere/reconciler.go
  pkg/controller/secretannotator/vsphere/reconciler_test.go
  pkg/vsphere/actuator/actuator.go
Labels: approved, lgtm, size/XXL
