Repository openshift/cloud-credential-operator, pull requests merged in 2020-09, with the labels that each got.

#240 Bug 1873345: specify a serviceaccount in the deployment
  manifests/05_deployment.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#246 Bug 1878163: move to go 1.15
  Dockerfile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#249 Bug 1880944: aws-pod-identity: add sideEffects to webhook
  bindata/v4.1.0/aws-pod-identity-webhook/mutatingwebhook.yaml
  pkg/assets/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#244 Bug 1871713: Mark Manual Clusters Upgradeable=False If 4.6 Cred Request Secrets Are Not Provisioned
  pkg/aws/actuator/actuator.go
  pkg/aws/actuator/actuator_test.go
  pkg/azure/actuator.go
  pkg/azure/passthrough.go
  pkg/gcp/actuator/actuator.go
  pkg/openstack/actuator.go
  pkg/operator/constants/constants.go
  pkg/operator/credentialsrequest/actuator/actuator.go
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
  pkg/operator/credentialsrequest/status.go
  pkg/operator/credentialsrequest/status_test.go
  pkg/operator/secretannotator/aws/reconciler.go
  pkg/ovirt/actuator.go
  pkg/vsphere/actuator/actuator.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#251 Bug 1882505: Fix stalled leader election after Deployment updates.
  manifests/03-deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
