Repository openshift/cloud-credential-operator, pull requests merged in 2020-11, with the labels that each got.

#263 Fix /etc/pki/ca-trust/extracted/pem permissions issue
  Dockerfile
  hack/writable-extracted.tar.gz
  manifests/03-deployment.yaml
Labels: approved, lgtm

#260 Add kubevirt platform
  README.md
  bindata/bootstrap/cloudcredential_v1_operator_config_custresdef.yaml
  go.mod
  go.sum
  manifests/00-config-custresdef.yaml
  pkg/apis/cloudcredential/v1/register.go
  pkg/apis/cloudcredential/v1/types_kubevirt.go
  pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  pkg/assets/bootstrap/bindata.go
  pkg/kubevirt/actuator.go
  pkg/kubevirt/actuator_test.go
  pkg/operator/constants/constants.go
  pkg/operator/controller.go
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
  pkg/operator/metrics/metrics.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#265 Revert "Fix /etc/pki/ca-trust/extracted/pem permissions issue"
  Dockerfile
  hack/writable-extracted.tar.gz
  manifests/03-deployment.yaml
Labels: approved, lgtm

#262 Bug 1889540: manifests: Allow 'for: 20m' for CloudCredentialOperatorDown
  manifests/0000_90_cloud-credential-operator_04_alertrules.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#266 aws: support custom CA bundle for AWS API
  pkg/aws/client.go
  pkg/operator/utils/aws/utils.go
Labels: approved, lgtm

#264 add new credentials field for AWS Secrets
  pkg/aws/actuator/actuator.go
  pkg/aws/actuator/actuator_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
Labels: approved, lgtm

#270 Bug 1880785: Fix CredentialsRequest missing description in 'oc explain'
  Makefile
  bindata/bootstrap/cloudcredential_v1_credentialsrequest_crd.yaml
  manifests/00-crd.yaml
  pkg/apis/cloudcredential/v1/types_credentialsrequest.go
  pkg/assets/bootstrap/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#253 Bug 1883412: Update upgradeable condition on admin cred changes.
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#274 Add IBM Cloud managed annotations to CVO manifests
  manifests/00-clusterreader_clusterrole.yaml
  manifests/00-crd.yaml
  manifests/00-namespace.yaml
  manifests/0000_90_cloud-credential-operator_01_prometheusrole.yaml
  manifests/0000_90_cloud-credential-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_cloud-credential-operator_03_servicemonitor.yaml
  manifests/01-cluster-role-binding.yaml
  manifests/01-cluster-role.yaml
  manifests/01-operator-config.yaml
  manifests/01-role-binding.yaml
  manifests/01-role.yaml
  manifests/01-service.yaml
  manifests/01-trusted-ca-configmap.yaml
  manifests/02-sa.yaml
Labels: approved, lgtm
