Repository openshift/cloud-credential-operator, pull requests merged in 2020-06, with the labels that each got.

#198 Ignore all idea files
  .gitignore
Labels: approved, lgtm

#188 Addition of Azure documentation
  README.md
Labels: approved, lgtm, ok-to-test

#197 add note explaining when legacy handling can be removed
  pkg/operator/utils/utils.go
Labels: approved, lgtm

#196 Updated README primarily to cover modes of operation.
  README.md
  docs/disabled-operator.md
  docs/mode-manual-creds.md
Labels: approved, lgtm

#199 prepare for moving to openshift/api
  pkg/apis/cloudcredential/v1/codec.go
  pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  pkg/apis/cloudcredential/v1/register.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/scheme/scheme.go
Labels: approved, lgtm

#201 Fix failing make install
  Makefile
Labels: approved, lgtm

#202 internalize location of CCO configmap
  pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  pkg/cmd/render/render.go
  pkg/operator/constants/constants.go
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
  pkg/operator/secretannotator/aws/reconciler.go
  pkg/operator/secretannotator/aws/reconciler_test.go
  pkg/operator/secretannotator/azure/reconciler.go
  pkg/operator/secretannotator/gcp/reconciler.go
  pkg/operator/secretannotator/gcp/reconciler_test.go
  pkg/operator/secretannotator/vsphere/reconciler.go
  pkg/operator/secretannotator/vsphere/reconciler_test.go
  pkg/operator/utils/utils.go
Labels: approved, lgtm

#203 report metric on mode of operator for CCO
  pkg/openstack/actuator.go
  pkg/operator/credentialsrequest/constants/constants.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_vsphere_test.go
  pkg/operator/metrics/metrics.go
  pkg/operator/metrics/metrics_test.go
  pkg/operator/platform/platform.go
  pkg/operator/secretannotator/aws/reconciler.go
  pkg/operator/secretannotator/azure/reconciler.go
  pkg/operator/secretannotator/constants/const.go
  pkg/operator/secretannotator/gcp/reconciler.go
  pkg/operator/secretannotator/vsphere/reconciler.go
  pkg/ovirt/actuator.go
Labels: approved, lgtm

#184 use alternate IAM endpoints if specified
  pkg/aws/actuator/actuator.go
  pkg/aws/actuator/actuator_test.go
  pkg/aws/client.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
  pkg/operator/oidcdiscoveryendpoint/controller.go
  pkg/operator/secretannotator/aws/reconciler.go
  pkg/operator/secretannotator/aws/reconciler_test.go
  pkg/operator/utils/aws/utils.go
  pkg/operator/utils/aws/utils_test.go
  pkg/operator/utils/utils.go
Labels: approved, lgtm

#200 Fix credentials request cleanup failure after re-enabling CCO
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
Labels: approved, lgtm

#206 Upgradable false when parent creds removed.
  README.md
  pkg/aws/actuator/actuator.go
  pkg/aws/actuator/actuator_test.go
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/azure/client.go
  pkg/azure/passthrough.go
  pkg/azure/passthrough_test.go
  pkg/gcp/actuator/actuator.go
  pkg/openstack/actuator.go
  pkg/operator/awspodidentity/controller.go
  pkg/operator/credentialsrequest/actuator/actuator.go
  pkg/operator/credentialsrequest/constants/constants.go
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
  pkg/operator/credentialsrequest/status.go
  pkg/operator/credentialsrequest/status_test.go
  pkg/ovirt/actuator.go
  pkg/vsphere/actuator/actuator.go
Labels: approved, lgtm

#211 Document an Azure manual credentials edge case.
  docs/mode-manual-creds.md
Labels: approved, lgtm

#192 support other Azure cloud environments
  go.mod
  go.sum
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/azure/clients.go
  pkg/azure/minter.go
  pkg/azure/passthrough_test.go
  pkg/operator/controller.go
  pkg/operator/secretannotator/azure/adal.go
  pkg/operator/secretannotator/azure/reconciler.go
  pkg/operator/secretannotator/azure/reconciler_test.go
  pkg/util/infra.go
  pkg/util/infra_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/install.go
  vendor/github.com/openshift/api/operator/v1/0000_20_etcd-operator_01.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/install.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/doc.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/register.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/types_conditioncheck.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#208 Bug 1809194: expose metrics over https
  manifests/0000_90_cloud-credential-operator_01_prometheusrole.yaml
  manifests/0000_90_cloud-credential-operator_03_servicemonitor.yaml
  manifests/0000_90_cloud-credential-operator_04_alertrules.yaml
  manifests/01-cluster-role.yaml
  manifests/01-service.yaml
  manifests/02-kube-rbac-proxy-config.yaml
  manifests/03-deployment.yaml
  manifests/image-references
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#212 no need for a non-default kube-rbac-proxy config
  manifests/0000_90_cloud-credential-operator_01_prometheusrole.yaml
  manifests/02-kube-rbac-proxy-config.yaml
  manifests/03-deployment.yaml
Labels: approved, lgtm

#205 unify constants
  pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  pkg/aws/actuator/actuator.go
  pkg/aws/actuator/actuator_test.go
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/azure/client.go
  pkg/azure/passthrough.go
  pkg/azure/passthrough_test.go
  pkg/azure/secret.go
  pkg/gcp/actuator/actuator.go
  pkg/openstack/actuator.go
  pkg/operator/constants/constants.go
  pkg/operator/credentialsrequest/actuator/actuator.go
  pkg/operator/credentialsrequest/constants/constants.go
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_vsphere_test.go
  pkg/operator/credentialsrequest/status.go
  pkg/operator/credentialsrequest/status_test.go
  pkg/operator/metrics/metrics.go
  pkg/operator/metrics/metrics_test.go
  pkg/operator/secretannotator/aws/reconciler.go
  pkg/operator/secretannotator/aws/reconciler_test.go
  pkg/operator/secretannotator/azure/reconciler.go
  pkg/operator/secretannotator/azure/reconciler_test.go
  pkg/operator/secretannotator/constants/const.go
  pkg/operator/secretannotator/gcp/reconciler.go
  pkg/operator/secretannotator/gcp/reconciler_test.go
  pkg/operator/secretannotator/vsphere/reconciler.go
  pkg/operator/secretannotator/vsphere/reconciler_test.go
  pkg/ovirt/actuator.go
  pkg/vsphere/actuator/actuator.go
Labels: approved, lgtm

#209 Bug 1846200: make AWS_POD_IDENTITY_WEBHOOK_IMAGE not set non-fatal
  pkg/operator/awspodidentity/controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#214 let CCO use the default info log-level
  manifests/03-deployment.yaml
Labels: approved, lgtm
