Repository openshift/cloud-credential-operator, pull requests merged in 2021-02, with the labels that each got.

#293 Bug 1916081: MissingTargetNamespace message fix
  manifests/0000_90_cloud-credential-operator_04_alertrules.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#290 Add initial documentation for using AWS Security Token Service
  README.md
  docs/sts.md
  docs/sts_flow.png
Labels: approved, lgtm

#291 specify Azure and GCP as supporting Manual mode
  README.md
Labels: approved, lgtm

#285 Add controller to cleanup stale credentials requests
  pkg/apis/cloudcredential/v1/types_credentialsrequest.go
  pkg/operator/cleanup/cleanup_controller.go
  pkg/operator/cleanup/cleanup_controller_test.go
  pkg/operator/cleanup/status.go
  pkg/operator/constants/constants.go
  pkg/operator/controller.go
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_vsphere_test.go
  pkg/operator/credentialsrequest/status.go
  pkg/operator/credentialsrequest/status_test.go
  pkg/operator/utils/utils.go
Labels: approved, lgtm

#279 Bug 1910372: Backport redistribute new root creds in passthrough mode
  bindata/bootstrap/cloudcredential_v1_credentialsrequest_crd.yaml
  manifests/00-crd.yaml
  pkg/apis/cloudcredential/v1/types_credentialsrequest.go
  pkg/assets/bootstrap/bindata.go
  pkg/aws/actuator/actuator.go
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/azure/passthrough.go
  pkg/azure/passthrough_test.go
  pkg/gcp/actuator/actuator.go
  pkg/openstack/actuator.go
  pkg/operator/credentialsrequest/actuator/actuator.go
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
  pkg/ovirt/actuator.go
  pkg/vsphere/actuator/actuator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#287 Bug 1916868: Check 47 creds backport
  pkg/aws/actuator/actuator.go
  pkg/gcp/actuator/actuator.go
  pkg/openstack/actuator.go
  pkg/operator/constants/constants.go
  pkg/operator/utils/utils.go
  pkg/vsphere/actuator/actuator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#300 Bug 1927925: spell fix user-visible string
  pkg/operator/utils/utils.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#296 new binary for setting up credentials outside of cluster
  cmd/ccoctl/main.go
  docs/ccoctl.md
  go.mod
  go.sum
  pkg/provisioning/create.go
  pkg/provisioning/create_test.go
  pkg/provisioning/keypair.go
  pkg/provisioning/keypair_test.go
  vendor/github.com/spf13/cobra/CHANGELOG.md
  vendor/github.com/spf13/cobra/CONTRIBUTING.md
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/custom_completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/fish_completions.md
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/modules.txt
Labels: approved, lgtm

#299 Add a CredentialsRequest field to store service account names
  bindata/bootstrap/cloudcredential_v1_credentialsrequest_crd.yaml
  manifests/00-crd.yaml
  pkg/apis/cloudcredential/v1/types_credentialsrequest.go
  pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  pkg/assets/bootstrap/bindata.go
Labels: approved, lgtm

#298 Add service account names to credentials request manifest
  manifests/05-iam-ro-credentialsrequest.yaml
Labels: approved, lgtm

#303 report STS as a submode of Manual
  pkg/aws/actuator/actuator.go
  pkg/operator/constants/constants.go
  pkg/operator/metrics/metrics.go
  pkg/operator/metrics/metrics_test.go
Labels: approved, lgtm
