Repository openshift/cloud-credential-operator, pull requests merged in 2021-06, with the labels that each got.

#336 Bug 1957446: v1beta to v1 for the CredentialsRequest CRD
  bindata/bootstrap/cloudcredential_v1_credentialsrequest_crd.yaml
  manifests/00-crd.yaml
  pkg/apis/apis.go
  pkg/assets/bootstrap/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#349 Bug 1960176: Make sure credentials have newly generated azure client secret
  pkg/azure/actuator.go
  pkg/gcp/actuator/actuator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#352 Bug 1970062: enable shared config files for AWS SDK
  pkg/cmd/provisioning/aws/aws.go
  pkg/cmd/provisioning/aws/create-iam-roles.go
  pkg/cmd/provisioning/aws/create_identity_provider.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#353 Bug 1970062: delete client should also use shared session function
  pkg/cmd/provisioning/aws/delete.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#351 Bug 1967531: Fix ccoctl delete not removing iam roles
  pkg/cmd/provisioning/aws/delete.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#354 Bug 1970062: use shared session setup in ccoctl create-all
  pkg/cmd/provisioning/aws/create_all.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#348 Remove checks inside conditional and use require.NotNil instead
  pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_vsphere_test.go
Labels: approved, lgtm

#326 Documentation to add a new cloud provider
  README.md
  docs/adding-new-cloud-provider.md
Labels: approved, lgtm

#358 Add code coverage script & make target
  .codecov.yml
  .gitignore
  Makefile
  hack/codecov.sh
Labels: approved, lgtm

#346 Add permissions boundary support to ccoctl when creating AWS IAM Roles
  pkg/cmd/provisioning/aws/aws.go
  pkg/cmd/provisioning/aws/create-iam-roles.go
  pkg/cmd/provisioning/aws/create-iam-roles_test.go
  pkg/cmd/provisioning/aws/create_all.go
Labels: approved, lgtm, ok-to-test
