Repository openshift/cloud-credential-operator, pull requests merged in 2021-04, with the labels that each got.

#311 installer manifests and 'all' subcommand
  docs/ccoctl.md
  pkg/cmd/provisioning/all.go
  pkg/cmd/provisioning/constants.go
  pkg/cmd/provisioning/create.go
  pkg/cmd/provisioning/identity_provider.go
  pkg/cmd/provisioning/identity_provider_test.go
  pkg/cmd/provisioning/keypair.go
  pkg/cmd/provisioning/keypair_test.go
  pkg/cmd/provisioning/roles.go
Labels: approved, lgtm

#314 Bug 1940142: Correct incorrect CACert in secrets created prior to 4.6
  go.mod
  go.sum
  pkg/openstack/actuator.go
  pkg/openstack/utils.go
  pkg/operator/secretannotator/openstack/reconciler.go
  pkg/operator/secretannotator/openstack/reconciler_test.go
  pkg/operator/secretannotator/secretannotator_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#319 Add management workload annotations
  manifests/00-namespace.yaml
  manifests/03-deployment.yaml
Labels: approved, lgtm

#317 Bug 1946097: oVirt credentials secret contains unnecessary "ovirt_cafile"
  README.md
  pkg/ovirt/actuator.go
  pkg/ovirt/actuator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#321 Bug 1948628: Add aws subcommand to ccoctl and additional UX changes
  cmd/ccoctl/main.go
  docs/ccoctl.md
  pkg/cmd/provisioning/all.go
  pkg/cmd/provisioning/aws/aws.go
  pkg/cmd/provisioning/aws/constants.go
  pkg/cmd/provisioning/aws/create-iam-roles.go
  pkg/cmd/provisioning/aws/create-iam-roles_test.go
  pkg/cmd/provisioning/aws/create_all.go
  pkg/cmd/provisioning/aws/create_identity_provider.go
  pkg/cmd/provisioning/aws/create_identity_provider_test.go
  pkg/cmd/provisioning/aws/create_key_pair.go
  pkg/cmd/provisioning/aws/create_key_pair_test.go
  pkg/cmd/provisioning/aws/delete.go
  pkg/cmd/provisioning/create.go
  pkg/cmd/provisioning/create_test.go
  pkg/cmd/provisioning/utils.go
  pkg/cmd/provisioning/utils_test.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#325 Bug 1948628: Fix ccoctl create aws iam-roles command and docs
  docs/ccoctl.md
  pkg/cmd/provisioning/aws/create-iam-roles.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#320 Bug 1927017: Use file observer for Proxy CA changes
  pkg/cmd/operator/cmd.go
  pkg/operator/configmap/configmap_controller.go
  pkg/operator/configmap/configmap_controller_test.go
  pkg/operator/controller.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/OWNERS
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#323 Bug 1949218: build and include ccoctl into image
  Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#329 Rename workload annotations
  manifests/03-deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#327 Bug 1949866: use initialization structure for ID provider
  pkg/cmd/provisioning/aws/create-iam-roles.go
  pkg/cmd/provisioning/aws/create_identity_provider.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#332 Bug 1952891: Fix OpenStack clouds.yaml updating in secretannotator
  pkg/operator/secretannotator/openstack/reconciler.go
  pkg/operator/secretannotator/openstack/reconciler_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
