Repository openshift/cloud-credential-operator, pull requests merged in 2021-09, with the labels that each got.

#378 update manual mode docs to cover new upgrade behavior
  docs/mode-manual-creds.md
Labels: approved, lgtm

#373 Update CI build root image to golang-1.16
  .ci-operator.yaml
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#379 Bug 1991770: The logLevel and operatorLogLevel values do not work with Cloud Credential Operator
  go.sum
  pkg/operator/controller.go
  pkg/operator/loglevel/controller.go
  pkg/operator/loglevel/controller_test.go
  pkg/operator/loglevel/status.go
  pkg/operator/utils/utils.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/robfig/cron/.gitignore
  vendor/github.com/robfig/cron/.travis.yml
  vendor/github.com/robfig/cron/LICENSE
  vendor/github.com/robfig/cron/README.md
  vendor/github.com/robfig/cron/constantdelay.go
  vendor/github.com/robfig/cron/cron.go
  vendor/github.com/robfig/cron/doc.go
  vendor/github.com/robfig/cron/parser.go
  vendor/github.com/robfig/cron/spec.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#385 Bug 2006364: fix(ibmcloud): Set policy attribute name properly for RG access
  pkg/cmd/provisioning/ibmcloud/service_id.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#387 Bug 1976674: make azure and ovirt consistent when in manual mode
  pkg/azure/actuator.go
  pkg/kubevirt/actuator.go
  pkg/ovirt/actuator.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#380 ibmcloud delete-service-id command
  pkg/cmd/provisioning/ibmcloud/create_service_id.go
  pkg/cmd/provisioning/ibmcloud/create_service_id_test.go
  pkg/cmd/provisioning/ibmcloud/delete_service_id.go
  pkg/cmd/provisioning/ibmcloud/ibmcloud.go
  pkg/cmd/provisioning/ibmcloud/service_id.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#390 Add UT for the delete-service-id command
  pkg/cmd/provisioning/ibmcloud/create_service_id_test.go
  pkg/cmd/provisioning/ibmcloud/delete_service_id_test.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved
