Repository openshift/cloud-credential-operator, pull requests merged in 2021-10, with the labels that each got.

#394 update OWNERS list
  OWNERS
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#383 Bug 2002152: Stop putting CCO in degraded state when stale credentials are found
  manifests/0000_90_cloud-credential-operator_04_alertrules.yaml
  pkg/operator/credentialsrequest/status.go
  pkg/operator/credentialsrequest/status_test.go
  pkg/operator/metrics/metrics.go
  pkg/operator/metrics/metrics_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#395 Bug 2010341: update alerts with summary and descriptions
  manifests/0000_90_cloud-credential-operator_04_alertrules.yaml
  pkg/aws/mock/client_generated.go
  pkg/azure/mock/client_generated.go
  pkg/gcp/mock/client_generated.go
  pkg/ibmcloud/mock/client_generated.go
  pkg/operator/secretannotator/azure/mock/adal_generated.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#388 Bug 1977319: cleanup orphaned Service 'controller-manager-service'
  manifests/01-service-delete.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low, qe-approved

#386 require spec.serviceAccountNames
  pkg/cmd/provisioning/aws/create-iam-roles.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#392 Defensive nil check in gcp actuator
  pkg/gcp/actuator/actuator.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#402 Bug 2015133: populate accountID when listing resource groups
  pkg/cmd/provisioning/ibmcloud/create_service_id.go
  pkg/cmd/provisioning/ibmcloud/refresh-keys.go
  pkg/cmd/provisioning/ibmcloud/utils.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low, qe-approved
