Repository openshift/cloud-credential-operator, pull requests merged in 2021-05, with the labels that each got.

#334 Bug 1954865: add priorityClass to pod-identity Deployment
  bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
  pkg/assets/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#335 Bug 1954615: do not assume result is valid after error
  pkg/operator/awspodidentity/controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#328 Bug 1949862: avoid referencing object after error
  pkg/cmd/provisioning/aws/create_identity_provider.go
  pkg/cmd/provisioning/aws/delete.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#333 Bug 1954765: v1beta1 to v1 mutatingwebhookconfiguration
  bindata/v4.1.0/aws-pod-identity-webhook/clusterrole.yaml
  bindata/v4.1.0/aws-pod-identity-webhook/mutatingwebhook.yaml
  pkg/assets/v410_00_assets/bindata.go
  pkg/operator/awspodidentity/controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#330 Bug 1953077: rework GCP passthrough permissions checking
  pkg/gcp/actuator/actuator.go
  pkg/gcp/client.go
  pkg/gcp/mock/client_generated.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/operator/secretannotator/gcp/reconciler_test.go
  pkg/operator/utils/gcp/utils.go
  pkg/operator/utils/gcp/utils_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#340 Bug 1958861: back to no CSR permissions for pod-id-webhook
  bindata/v4.1.0/aws-pod-identity-webhook/clusterrole.yaml
  pkg/assets/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#341 Bug 1864116: Fix "unsupported platform type" log spamming on BareMetal.
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#342 Bug 1910396: Add ErrorScrub utility to prevent infinite update/reconc…
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
  pkg/operator/utils/errorscrub.go
  pkg/operator/utils/errorscrub_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#343 Bug 1962602: Remove log statement in frequently called function.
  pkg/operator/status/status_controller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#345 Bug 1960176: Recreate user when deleted in cloud providers
  pkg/aws/actuator/actuator.go
  pkg/azure/actuator.go
  pkg/gcp/actuator/actuator.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
