Repository openshift/cloud-credential-operator, pull requests merged in 2021-12, with the labels that each got.

#422 Add doc for ibmcloud
  docs/ccoctl.md
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#436 Bug 2035328: Make ccoctl ignore cred requests marked for deletion
  go.mod
  pkg/aws/mock/client_generated.go
  pkg/azure/mock/client_generated.go
  pkg/cmd/provisioning/aws/create-iam-roles_test.go
  pkg/cmd/provisioning/ibmcloud/create_service_id.go
  pkg/cmd/provisioning/ibmcloud/delete_service_id.go
  pkg/cmd/provisioning/ibmcloud/refresh-keys.go
  pkg/cmd/provisioning/utils.go
  pkg/gcp/mock/client_generated.go
  pkg/ibmcloud/mock/client_generated.go
  pkg/operator/secretannotator/azure/mock/adal_generated.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/classicadministrators.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/globaladministrator.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/permissions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/provideroperationsmetadata.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/roleassignments.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/roledefinitions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/version.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#438 Bug 2035315: fix passthrough test cases
  pkg/aws/actuator/actuator.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
