Repository openshift/cloud-credential-operator, pull requests merged in 2021-11, with the labels that each got.

#408 Add ccoctl gcp command to create all the required credentials infra
  pkg/cmd/provisioning/gcp/create_all.go
  pkg/cmd/provisioning/gcp/gcp.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#415 Fix small log typo for upgradable check
  pkg/operator/utils/utils.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#375 Add usage docs for ccoctl gcp
  docs/ccoctl.md
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#419 Minor corrections to gcp workload identity docs
  README.md
  docs/gcp_workload_identity.md
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#417 Bug 2023832: pkg/operator/status: Only bump lastTransitionTime on status changes
  pkg/operator/status/status_controller.go
  pkg/operator/status/status_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#421 Bug 2024613: pod-identity-webhook starts without tls
  bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
  pkg/assets/v410_00_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#424 [release-4.9] Bug 2024751: pod-identity-webhook starts without tls
  .ci-operator.yaml
  go.sum
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#397 [release-4.9] Bug 1992563: update alerts with summary and descriptions
  manifests/0000_90_cloud-credential-operator_04_alertrules.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed
