Repository openshift/cloud-credential-operator, pull requests merged in 2022-10, with the labels that each got.

#494 Update OWNERS to reflect reality.
  OWNERS
Labels: approved, lgtm

#495 Changes generated from make update-gofmt with go-1.19.
  .ci-operator.yaml
  Dockerfile
  pkg/assets/bootstrap/bindata.go
  pkg/assets/v410_00_assets/bindata.go
  pkg/aws/actuator/actuator.go
  pkg/cmd/provisioning/alibabacloud/create-ram-users.go
  pkg/cmd/provisioning/alibabacloud/delete-ram-users.go
  pkg/cmd/provisioning/alibabacloud/utils.go
  pkg/gcp/actuator/actuator.go
  pkg/kubevirt/actuator.go
  pkg/openstack/actuator.go
  pkg/openstack/utils.go
  pkg/operator/credentialsrequest/actuator/actuator.go
  pkg/operator/utils/utils.go
  pkg/ovirt/actuator.go
  pkg/vsphere/actuator/actuator.go
Labels: approved, lgtm, bugzilla/valid-bug

#500 [release-4.11] OCPBUGS-2278: Add ccoctl support to create OIDC endpoint with private S3 bucket
  docs/ccoctl.md
  docs/sts-private-bucket.md
  docs/sts.md
  pkg/aws/client.go
  pkg/aws/mock/client_generated.go
  pkg/cmd/provisioning/aws/aws.go
  pkg/cmd/provisioning/aws/create_all.go
  pkg/cmd/provisioning/aws/create_identity_provider.go
  pkg/cmd/provisioning/aws/create_identity_provider_test.go
  pkg/cmd/provisioning/aws/delete.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/api.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/cloudfrontiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/doc.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/errors.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/service.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/waiters.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#501 [release-4.10] OCPBUGS-2279: Add ccoctl support to create OIDC endpoint with private S3 bucket
  docs/ccoctl.md
  docs/sts-private-bucket.md
  docs/sts.md
  pkg/aws/client.go
  pkg/aws/mock/client_generated.go
  pkg/cmd/provisioning/aws/aws.go
  pkg/cmd/provisioning/aws/create_all.go
  pkg/cmd/provisioning/aws/create_identity_provider.go
  pkg/cmd/provisioning/aws/create_identity_provider_test.go
  pkg/cmd/provisioning/aws/delete.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/api.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/cloudfrontiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/doc.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/errors.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/service.go
  vendor/github.com/aws/aws-sdk-go/service/cloudfront/waiters.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#491 Make ccoctl use regional STS endpoint by default
  docs/sts.md
  pkg/cmd/provisioning/aws/create-iam-roles.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved
