Repository openshift/cloud-credential-operator, pull requests merged in 2023-11, with the labels that each got.

#611 CCO-430: Use per-project custom roles instead of per-cluster custom roles
  pkg/cmd/provisioning/gcp/create_all.go
  pkg/cmd/provisioning/gcp/create_service_accounts.go
  pkg/cmd/provisioning/gcp/create_service_accounts_test.go
  pkg/cmd/provisioning/gcp/create_workload_identity_provider.go
  pkg/cmd/provisioning/gcp/delete.go
  pkg/gcp/actuator/actuator.go
  pkg/gcp/actuator/policy.go
  pkg/gcp/actuator/role.go
  pkg/gcp/actuator/utils.go
  pkg/gcp/actuator/utils_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
Labels: approved, lgtm, jira/valid-reference

#617 NO-ISSUE: Removing andrew from OWNERS
  OWNERS
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#627 CCO-192: Use Leases for leader election
  pkg/cmd/operator/cmd.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#628 OCPBUGS-20478: Explicitly set the vsphere secret credential data on sync.
  pkg/vsphere/actuator/actuator.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#587 CCO-372: Azure Workload Identity info in CredsRequests creates a Secret
  Makefile
  pkg/apis/cloudcredential/v1/types_azure.go
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/azure/const.go
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
  test/e2e/azure/azident/actutator_e2e_test.go
Labels: approved, lgtm, jira/valid-reference
