Repository openshift/cloud-credential-operator, pull requests merged in 2023-08, with the labels that each got.

#573 CCO-402: Create Azure AD pod identity webhook config secret manifest in create-all,create-oidc-issuer
  docs/azure_workload_identity.md
  docs/ccoctl.md
  pkg/cmd/provisioning/azure/azure.go
  pkg/cmd/provisioning/azure/create_all.go
  pkg/cmd/provisioning/azure/create_oidc_issuer.go
  pkg/cmd/provisioning/azure/create_oidc_issuer_test.go
Labels: approved, lgtm, jira/valid-reference

#584 CCO-413: Add dataPermissions to Azure credentials request.
  pkg/apis/cloudcredential/v1/types_azure.go
  pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  pkg/cmd/provisioning/azure/create_managed_identities.go
Labels: approved, lgtm, jira/valid-reference

#586 CCO-401: Add azure-workload-identity-webhook to image references.
  manifests/image-references
Labels: approved, lgtm, jira/valid-reference

#588 Revert "CCO-401: Add azure-workload-identity-webhook to image references."
  manifests/image-references
Labels: approved, jira/valid-reference

#585 OCPBUGS-17049: update lastSyncGeneration in STS flow sync success
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#583 OCPBUGS-16684: Set cr.status.provisioned=false on syncErr path
  pkg/aws/actuator/actuator.go
  pkg/aws/actuator/actuator_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#559 CCO-363: Adding azure identity webhook
  bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
  bindata/v4.1.0/aws-pod-identity-webhook/mutatingwebhook.yaml
  bindata/v4.1.0/azure-pod-identity-webhook/deployment.yaml
  bindata/v4.1.0/azure-pod-identity-webhook/mutatingwebhook.yaml
  bindata/v4.1.0/common/clusterrole.yaml
  bindata/v4.1.0/common/clusterrolebinding.yaml
  bindata/v4.1.0/common/poddisruptionbudget.yaml
  bindata/v4.1.0/common/role.yaml
  bindata/v4.1.0/common/rolebinding.yaml
  bindata/v4.1.0/common/sa.yaml
  bindata/v4.1.0/common/svc.yaml
  manifests/03-deployment.yaml
  manifests/image-references
  pkg/assets/v410_00_assets/bindata.go
  pkg/operator/awspodidentity/awspodidentitywebhook_controller_test.go
  pkg/operator/controller.go
  pkg/operator/podidentity/awspodidentitywebhook.go
  pkg/operator/podidentity/azurepodidentitywebhook.go
  pkg/operator/podidentity/podidentitywebhook_controller.go
  pkg/operator/podidentity/podidentitywebhook_controller_test.go
Labels: approved, lgtm, jira/valid-reference

#590 pkg/aws/actuator: Drop comment which suggested passthrough permission verification
  pkg/aws/actuator/actuator.go
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#591 OCPBUGS-17719: Double timeout delays for managed identity creation and role assignment from 2 to 4 minutes.
  pkg/cmd/provisioning/azure/create_managed_identities.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
