Repository openshift/cloud-credential-operator, pull requests merged in 2023-10, with the labels that each got.

#603 Docs: azure workload identity no longer requires TechPreviewNoUpgrade
  docs/azure_workload_identity.md
Labels: approved, lgtm

#604 Revert #592 "CCO-421: *: split pod identity webhooks from core controller"
  cmd/cloud-credential-operator/main.go
  manifests/01-cluster-role.yaml
  manifests/01-webhook-cluster-role-binding.yaml
  manifests/01-webhook-cluster-role.yaml
  manifests/01-webhook-role-binding.yaml
  manifests/01-webhook-role.yaml
  manifests/02-webhook-sa.yaml
  manifests/03-deployment.yaml
  manifests/03-webhook-deployment.yaml
  pkg/cmd/webhookoperator/cmd.go
  pkg/operator/controller.go
  pkg/operator/podidentity/podidentitywebhook_controller.go
Labels: approved, lgtm, jira/valid-reference

#606 Removing andrew from OWNERS
  OWNERS
Labels: approved

#607 OCPBUGS-21745: azure create-managed-identites to add cloud controller manager to network resource group
  pkg/cmd/provisioning/azure/create_managed_identities.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#610 OCPBUGS-22369: explicitly set azure oidc bucket to allow public blob access
  pkg/cmd/provisioning/azure/create_oidc_issuer.go
  pkg/cmd/provisioning/azure/create_oidc_issuer_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#613 snyk: exclude vendor/
  .snyk
Labels: approved, lgtm
