Repository openshift/cloud-credential-operator, pull requests merged in 2023-03, with the labels that each got.

#517 Bump golang.org/x/net from v0.5.0 to v0.7.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/golang.org/x/sys/unix/gccgo_c.c
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/timestruct.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#519 Upgrade build-machinery-go: `make vulncheck`
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/test-unit.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/vulncheck.mk
  vendor/github.com/openshift/build-machinery-go/scripts/vulncheck.sh
  vendor/modules.txt
Labels: approved, lgtm, docs-approved, qe-approved, px-approved

#520 OCPBUGS-8666: feat: add workload annotation to pod identity webhook deployment
  bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
  pkg/assets/v410_00_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#515 SPLAT-950: doc/aws-sts : steps to migrate from public bucket to private issuer URL
  docs/sts-migrate-to-private-bucket.md
  docs/sts-oidc-bucket-policy.json.tpl
  docs/sts-oidc-cloudfront.json.tpl
  docs/sts-private-bucket.md
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, jira/valid-reference

#522 OCPBUGS-8666: Correct pod-identity-webhook annotations for PreferredDuringScheduling.
  bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
  pkg/assets/v410_00_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#524 [release-4.13] OCPBUGS-10822: Adding missing workload annotations
  bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
  pkg/assets/v410_00_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
