Repository openshift/cloud-credential-operator, pull requests merged in 2023-07, with the labels that each got.

#547 CCO-394: Do not Add PodIdentityWebhook controller when InfraStatus.ControlPlaneToplogy is External.
  pkg/operator/awspodidentity/awspodidentitywebhook_controller.go
Labels: approved, lgtm, jira/valid-reference

#556 CCO-353: ccoctl to create azure custom roles
  pkg/apis/cloudcredential/v1/types_azure.go
  pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  pkg/azure/clients.go
  pkg/azure/mock/client_generated.go
  pkg/cmd/provisioning/azure/create_managed_identities.go
  pkg/cmd/provisioning/azure/create_managed_identities_test.go
  pkg/cmd/provisioning/azure/delete.go
Labels: approved, lgtm, jira/valid-reference

#560 reconcile status when the clusteroperator changes
  pkg/operator/status/status_controller.go
Labels: approved, lgtm

#545 OCPBUGS-15365: *: use a filtered LIST + WATCH on Secrets for AWS STS
  go.mod
  manifests/04-cluster-operator.yaml
  pkg/apis/cloudcredential/v1/types_credentialsrequest.go
  pkg/aws/actuator/actuator.go
  pkg/aws/actuator/actuator_test.go
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/azure/client.go
  pkg/cmd/operator/cmd.go
  pkg/gcp/actuator/actuator.go
  pkg/kubevirt/actuator.go
  pkg/kubevirt/actuator_test.go
  pkg/openstack/actuator.go
  pkg/operator/awspodidentity/awspodidentitywebhook_controller.go
  pkg/operator/cleanup/cleanup_controller.go
  pkg/operator/controller.go
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_azure_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_label_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_vsphere_test.go
  pkg/operator/loglevel/controller.go
  pkg/operator/metrics/metrics.go
  pkg/operator/platform/platform.go
  pkg/operator/secretannotator/secretannotator_controller.go
  pkg/operator/status/status_controller.go
  pkg/ovirt/actuator.go
  pkg/vsphere/actuator/actuator.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#561 Revert "Merge pull request #398 from csrwng/exclude_config_ibmcloud"
  manifests/01-operator-config.yaml
  manifests/01-service.yaml
  manifests/04-cluster-operator.yaml
Labels: approved, lgtm

#562 OCPBUGS-16036: Set status on CR properly when STS provisioned
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#565 OCPBUGS-16088: Adds [default] section header to STS Secrets
  pkg/aws/actuator/actuator.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#564 OCPBUGS-15906: ccoctl azure delete to also delete role assignments
  pkg/cmd/provisioning/azure/create_managed_identities.go
  pkg/cmd/provisioning/azure/delete.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#567 OCPBUGS-15365: manifests: fix rbac
  manifests/01-role.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#570 Revert "manifests: manually amend resources that get laid down by CVO in HCP"
  manifests/01-service.yaml
  manifests/04-cluster-operator.yaml
Labels: approved, lgtm

#572 OCPBUGS-16313: manifests: allow list/watch globally on our config configmap
  manifests/01-cluster-role.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#568 OCPBUGS-16334: Clarify updateActuatorConditions & update lastSync
  pkg/operator/credentialsrequest/credentialsrequest_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#575 OCPBUGS-16313: pkg/operator: correctly fetch CA for AWS minter
  manifests/01-cluster-role.yaml
  manifests/01-config-role-binding.yaml
  manifests/01-config-role.yaml
  pkg/aws/actuator/actuator.go
  pkg/cmd/operator/cmd.go
  pkg/operator/controller.go
  pkg/operator/secretannotator/aws/reconciler.go
  pkg/operator/utils/client.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#576 *: use a global codec
  manifests/03-deployment.yaml
  pkg/apis/cloudcredential/v1/codec.go
  pkg/aws/actuator/actuator.go
  pkg/aws/actuator/actuator_test.go
  pkg/aws/utils.go
  pkg/azure/actuator.go
  pkg/azure/actuator_test.go
  pkg/azure/request.go
  pkg/cmd/operator/cmd.go
  pkg/cmd/provisioning/alibabacloud/create-ram-users.go
  pkg/cmd/provisioning/aws/create-iam-roles.go
  pkg/cmd/provisioning/azure/create_managed_identities.go
  pkg/cmd/provisioning/gcp/create_service_accounts.go
  pkg/cmd/provisioning/ibmcloud/service_id.go
  pkg/cmd/provisioning/nutanix/create_shared_secrets.go
  pkg/gcp/actuator/actuator.go
  pkg/kubevirt/actuator_test.go
  pkg/openstack/actuator.go
  pkg/operator/cleanup/cleanup_controller_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_azure_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_gcp_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_test.go
  pkg/operator/credentialsrequest/credentialsrequest_controller_vsphere_test.go
  pkg/operator/credentialsrequest/status_test.go
  pkg/operator/metrics/metrics_test.go
  pkg/operator/utils/utils.go
  pkg/ovirt/actuator.go
  pkg/vsphere/actuator/actuator.go
  test/e2e/aws/sts/actutator_e2e_test.go
Labels: approved, lgtm

#566 CCO-233: Add Azure AD Workload Identity doc.
  README.md
  docs/azure_ad_workload_identity_flow.png
  docs/azure_workload_identity.md
  docs/ccoctl.md
Labels: approved, lgtm, jira/valid-reference

#578 OCPBUGS-16614: go.mod: re-vendor openshift/api
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#577 Add DOCKER_CMD Makefile var to use podman when found.
  Makefile
Labels: approved, lgtm

#581 OCPCLOUD-2012: ccoctl: Add --enable-tech-preview arg to azure create-all subcommand.
  pkg/cmd/provisioning/azure/create_all.go
Labels: approved, lgtm, jira/valid-reference

#582 OCPBUGS-16807: ccoctl azure exit with error when OIDC and installation resource group names are the same
  pkg/cmd/provisioning/azure/create_all.go
  pkg/cmd/provisioning/azure/create_managed_identities.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#580 OCPCLOUD-2012: ccoctl: Plumb credreq.spec.cloudTokenPath override into Azure secret creation
  bindata/bootstrap/cloudcredential_v1_credentialsrequest_crd.yaml
  manifests/00-crd.yaml
  pkg/apis/cloudcredential/v1/types_credentialsrequest.go
  pkg/assets/bootstrap/bindata.go
  pkg/cmd/provisioning/azure/create_managed_identities.go
  pkg/cmd/provisioning/azure/create_managed_identities_test.go
Labels: approved, lgtm, jira/valid-reference
