Repository openshift/cloud-credential-operator, pull requests merged in 2023-12, with the labels that each got.

#596 OCPBUGS-13597: Discover AWS dns suffix from partition and region.
  pkg/cmd/provisioning/aws/create_identity_provider.go
  pkg/cmd/provisioning/aws/create_identity_provider_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#637 OCPBUGS-23178: Enable GCP sync to undelete custom roles
  pkg/gcp/actuator/actuator.go
  pkg/gcp/actuator/policy.go
  pkg/gcp/actuator/role.go
  pkg/gcp/client.go
  pkg/gcp/mock/client_generated.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#626 CCO-244: gcp-ro-credentialrequest to use granular permissions
  manifests/05-gcp-ro-credentialsrequest.yaml
Labels: approved, lgtm, qe-approved, jira/valid-reference

#638 CCO-338: cmd/operator: use correct kubeconfig for all clients
  pkg/cmd/operator/cmd.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/doc.go
Labels: approved, lgtm, jira/valid-reference

#634 NO-JIRA: Update docs/sts.md
  docs/sts.md
Labels: approved, lgtm, needs-ok-to-test, jira/valid-reference
