Repository openshift/cloud-credential-operator, pull requests merged in 2024-12, with the labels that each got.

#790 NO-JIRA: docs: rotate oidc key to specify azure storage account variables
  docs/rotate-oidc-key.md
Labels: approved, lgtm, jira/valid-reference

#781 OCPBUGS-44933: Add retry to ccoctl gcp create functions
  pkg/cmd/provisioning/azure/create_managed_identities.go
  pkg/cmd/provisioning/gcp/create_service_accounts.go
  pkg/cmd/provisioning/gcp/create_workload_identity_provider.go
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#762 NO-JIRA: Fix JSON for 07-block-public-access-to-oidc-bucket.json
  pkg/cmd/provisioning/aws/create_identity_provider.go
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#797 NO-JIRA: docs: rotate azure key to use more accurate variable commands
  docs/rotate-oidc-key.md
Labels: approved, lgtm, jira/valid-reference

#789 OCPBUGS-41727: Add AWS region to aws-pod-identity-webhook
  bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
  pkg/assets/v410_00_assets/bindata.go
  pkg/operator/podidentity/awspodidentitywebhook.go
  pkg/operator/podidentity/azurepodidentitywebhook.go
  pkg/operator/podidentity/gcppodidentitywebhook.go
  pkg/operator/podidentity/podidentitywebhook_controller.go
  pkg/operator/podidentity/podidentitywebhook_controller_test.go
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#799 [release-4.17] OCPBUGS-45938: Add AWS region to aws-pod-identity-webhook
  bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
  pkg/assets/v410_00_assets/bindata.go
  pkg/operator/podidentity/awspodidentitywebhook.go
  pkg/operator/podidentity/azurepodidentitywebhook.go
  pkg/operator/podidentity/gcppodidentitywebhook.go
  pkg/operator/podidentity/podidentitywebhook_controller.go
  pkg/operator/podidentity/podidentitywebhook_controller_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#800 [release-4.16] OCPBUGS-45939: Add AWS region to aws-pod-identity-webhook
  bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
  pkg/assets/v410_00_assets/bindata.go
  pkg/operator/podidentity/awspodidentitywebhook.go
  pkg/operator/podidentity/azurepodidentitywebhook.go
  pkg/operator/podidentity/podidentitywebhook_controller.go
  pkg/operator/podidentity/podidentitywebhook_controller_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
