Repository openshift/cloud-credential-operator, pull requests merged in 2024-05, with the labels that each got.

#696 OCPBUGS-32900: Upgrade go-jose module to 2.6.3
  go.mod
  go.sum
  pkg/cmd/provisioning/aws/create_identity_provider.go
  pkg/cmd/provisioning/utils.go
  vendor/gopkg.in/go-jose/go-jose.v2/.gitcookies.sh.enc
  vendor/gopkg.in/go-jose/go-jose.v2/.gitignore
  vendor/gopkg.in/go-jose/go-jose.v2/.travis.yml
  vendor/gopkg.in/go-jose/go-jose.v2/CHANGELOG.md
  vendor/gopkg.in/go-jose/go-jose.v2/CONTRIBUTING.md
  vendor/gopkg.in/go-jose/go-jose.v2/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/asymmetric.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/cbc_hmac.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/concat_kdf.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/key_wrap.go
  vendor/gopkg.in/go-jose/go-jose.v2/crypter.go
  vendor/gopkg.in/go-jose/go-jose.v2/doc.go
  vendor/gopkg.in/go-jose/go-jose.v2/encoding.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/json/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/json/decode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/encode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/indent.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/scanner.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/stream.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/tags.go
  vendor/gopkg.in/go-jose/go-jose.v2/jwe.go
  vendor/gopkg.in/go-jose/go-jose.v2/jwk.go
  vendor/gopkg.in/go-jose/go-jose.v2/jws.go
  vendor/gopkg.in/go-jose/go-jose.v2/opaque.go
  vendor/gopkg.in/go-jose/go-jose.v2/shared.go
  vendor/gopkg.in/go-jose/go-jose.v2/signing.go
  vendor/gopkg.in/go-jose/go-jose.v2/symmetric.go
  vendor/gopkg.in/square/go-jose.v2/BUG-BOUNTY.md
  vendor/gopkg.in/square/go-jose.v2/README.md
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#697 OCPBUGS-32899: Upgrade go-jose module to 2.6.3
  go.mod
  go.sum
  pkg/cmd/provisioning/aws/create_identity_provider.go
  pkg/cmd/provisioning/utils.go
  vendor/gopkg.in/go-jose/go-jose.v2/.gitcookies.sh.enc
  vendor/gopkg.in/go-jose/go-jose.v2/.gitignore
  vendor/gopkg.in/go-jose/go-jose.v2/.travis.yml
  vendor/gopkg.in/go-jose/go-jose.v2/CHANGELOG.md
  vendor/gopkg.in/go-jose/go-jose.v2/CONTRIBUTING.md
  vendor/gopkg.in/go-jose/go-jose.v2/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/asymmetric.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/cbc_hmac.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/concat_kdf.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/key_wrap.go
  vendor/gopkg.in/go-jose/go-jose.v2/crypter.go
  vendor/gopkg.in/go-jose/go-jose.v2/doc.go
  vendor/gopkg.in/go-jose/go-jose.v2/encoding.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/json/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/json/decode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/encode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/indent.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/scanner.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/stream.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/tags.go
  vendor/gopkg.in/go-jose/go-jose.v2/jwe.go
  vendor/gopkg.in/go-jose/go-jose.v2/jwk.go
  vendor/gopkg.in/go-jose/go-jose.v2/jws.go
  vendor/gopkg.in/go-jose/go-jose.v2/opaque.go
  vendor/gopkg.in/go-jose/go-jose.v2/shared.go
  vendor/gopkg.in/go-jose/go-jose.v2/signing.go
  vendor/gopkg.in/go-jose/go-jose.v2/symmetric.go
  vendor/gopkg.in/square/go-jose.v2/BUG-BOUNTY.md
  vendor/gopkg.in/square/go-jose.v2/README.md
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#698 OCPBUGS-32898: Upgrade go-jose module to 2.6.3
  go.mod
  go.sum
  pkg/cmd/provisioning/aws/create_identity_provider.go
  pkg/cmd/provisioning/utils.go
  vendor/gopkg.in/go-jose/go-jose.v2/.gitcookies.sh.enc
  vendor/gopkg.in/go-jose/go-jose.v2/.gitignore
  vendor/gopkg.in/go-jose/go-jose.v2/.travis.yml
  vendor/gopkg.in/go-jose/go-jose.v2/CHANGELOG.md
  vendor/gopkg.in/go-jose/go-jose.v2/CONTRIBUTING.md
  vendor/gopkg.in/go-jose/go-jose.v2/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/asymmetric.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/cbc_hmac.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/concat_kdf.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/key_wrap.go
  vendor/gopkg.in/go-jose/go-jose.v2/crypter.go
  vendor/gopkg.in/go-jose/go-jose.v2/doc.go
  vendor/gopkg.in/go-jose/go-jose.v2/encoding.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/json/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/json/decode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/encode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/indent.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/scanner.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/stream.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/tags.go
  vendor/gopkg.in/go-jose/go-jose.v2/jwe.go
  vendor/gopkg.in/go-jose/go-jose.v2/jwk.go
  vendor/gopkg.in/go-jose/go-jose.v2/jws.go
  vendor/gopkg.in/go-jose/go-jose.v2/opaque.go
  vendor/gopkg.in/go-jose/go-jose.v2/shared.go
  vendor/gopkg.in/go-jose/go-jose.v2/signing.go
  vendor/gopkg.in/go-jose/go-jose.v2/symmetric.go
  vendor/gopkg.in/square/go-jose.v2/BUG-BOUNTY.md
  vendor/gopkg.in/square/go-jose.v2/README.md
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#699 OCPBUGS-32897: Upgrade go-jose module to 2.6.3
  go.mod
  go.sum
  pkg/cmd/provisioning/aws/create_identity_provider.go
  pkg/cmd/provisioning/utils.go
  vendor/gopkg.in/go-jose/go-jose.v2/.gitcookies.sh.enc
  vendor/gopkg.in/go-jose/go-jose.v2/.gitignore
  vendor/gopkg.in/go-jose/go-jose.v2/.travis.yml
  vendor/gopkg.in/go-jose/go-jose.v2/CHANGELOG.md
  vendor/gopkg.in/go-jose/go-jose.v2/CONTRIBUTING.md
  vendor/gopkg.in/go-jose/go-jose.v2/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/asymmetric.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/cbc_hmac.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/concat_kdf.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/key_wrap.go
  vendor/gopkg.in/go-jose/go-jose.v2/crypter.go
  vendor/gopkg.in/go-jose/go-jose.v2/doc.go
  vendor/gopkg.in/go-jose/go-jose.v2/encoding.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/json/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/json/decode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/encode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/indent.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/scanner.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/stream.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/tags.go
  vendor/gopkg.in/go-jose/go-jose.v2/jwe.go
  vendor/gopkg.in/go-jose/go-jose.v2/jwk.go
  vendor/gopkg.in/go-jose/go-jose.v2/jws.go
  vendor/gopkg.in/go-jose/go-jose.v2/opaque.go
  vendor/gopkg.in/go-jose/go-jose.v2/shared.go
  vendor/gopkg.in/go-jose/go-jose.v2/signing.go
  vendor/gopkg.in/go-jose/go-jose.v2/symmetric.go
  vendor/gopkg.in/square/go-jose.v2/BUG-BOUNTY.md
  vendor/gopkg.in/square/go-jose.v2/README.md
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#701 OCPBUGS-32948: Update documentation to restart pods when enabling workload identity
  docs/azure_workload_identity.md
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#702 OCPBUGS-33621: docs: Azure WI migration to extract only the credentialRequests needed by the cluster.
  docs/azure_workload_identity.md
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#703 OCPBUGS-33566: AWS STS should not error when a credentailsRequest does not have awsSTSIAMRoleARN
  pkg/aws/actuator/actuator.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
