Repository openshift/cloud-credential-operator, pull requests merged in 2024-02, with the labels that each got.

#649 [release-4.15] OCPBUGS-27910: Resolve all outstanding snyk vulnerabilities
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions_defaults.binpb
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#667 OCPBUGS-28535: stop LoadInfrastructureRegion from panicking when being called on a non-AWS cluster
  pkg/operator/secretannotator/aws/reconciler_test.go
  pkg/operator/utils/aws/utils.go
  pkg/operator/utils/utils.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#654 OCPBUGS-27214: ccoctl - use proxy when validating CloudFront URL
  pkg/cmd/provisioning/aws/create_identity_provider.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#665 OCPBUGS-28388: Fix the ClusterOperator watch of the status controller
  pkg/operator/status/status_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#672 OCPBUGS-28230: add FallbackToLogsOnError for easier debugging
  bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
  bindata/v4.1.0/azure-pod-identity-webhook/deployment.yaml
  pkg/assets/v410_00_assets/bindata.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#669 NO-JIRA: Fix update-codegen.sh
  hack/update-codegen.sh
Labels: approved, lgtm, jira/valid-reference

#677 NO-JIRA:docu change: fix find command
  docs/sts.md
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#670 OCPBUGS-28231: Guard upgrading GCP from 4.14 to 4.15 without RoleAdmin permissions
  pkg/aws/actuator/actuator.go
  pkg/azure/actuator.go
  pkg/gcp/actuator/actuator.go
  pkg/kubevirt/actuator.go
  pkg/openstack/actuator.go
  pkg/operator/utils/utils.go
  pkg/operator/utils/utils_test.go
  pkg/ovirt/actuator.go
  pkg/vsphere/actuator/actuator.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#680 CCO-525: Azure workload identity doc updates
  docs/azure_workload_identity.md
Labels: approved, lgtm, jira/valid-reference
