Repository openshift/cloud-credential-operator, pull requests merged in 2025-09, with the labels that each got.

#914 OCPBUGS-61475: set cloud-credential-operator as default-container
  manifests/03-deployment.yaml
Labels: approved, lgtm, ok-to-test, jira/severity-low, jira/valid-bug, jira/valid-reference, verified

#915 OCPBUGS-55127: snyk to ignore SNYK-GOLANG-GOLANGORGXNETHTML-9572088
  .snyk
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference, verified

#921 OCPBUGS-62184: aws: remove endpoint overrides for s3 and cf clients
  pkg/aws/client.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, verified
