Repository openshift/cloud-credential-operator, pull requests merged in 2025-07, with the labels that each got.

#884 OCPBUGS-59511: add read only filesystem
  pkg/cmd/render/render.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#890 OCPBUGS-59401: github.com/golang/glog v1.2.5
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#892 OCPBUGS-58679: github.com/golang/glog v1.2.5
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#893 OCPBUGS-58676: github.com/golang/glog v1.2.5
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#889 NO-JIRA: Drop lleshchi from OWNERS
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#894 OCPBUGS-58678: github.com/golang/glog v1.2.5
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#895 OCPBUGS-58677: github.com/golang/glog v1.2.5
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference
