Repository openshift/cloud-credential-operator, pull requests merged in 2025-03, with the labels that each got.

#820 NO-JIRA: add example of how to build from source
  README.md
Labels: approved, lgtm, jira/valid-reference

#818 NO-JIRA: Add dry-run on aws create-all command
  pkg/cmd/provisioning/aws/create-iam-roles.go
  pkg/cmd/provisioning/aws/create_all.go
Labels: approved, lgtm, jira/valid-reference

#823 OCPBUGS-52507: github.com/go-jose/go-jose/v4 v4.0.5
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#819 CCO-647: Enable readOnlyRootFilesystem on all containers
  bindata/v4.1.0/aws-pod-identity-webhook/deployment.yaml
  bindata/v4.1.0/azure-pod-identity-webhook/deployment.yaml
  bindata/v4.1.0/gcp-pod-identity-webhook/deployment.yaml
  manifests/03-deployment.yaml
  pkg/assets/v410_00_assets/bindata.go
Labels: approved, lgtm, jira/valid-reference

#824 OCPBUGS-51237: github.com/go-jose/go-jose/v4 v4.0.5
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v4/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/crypter.go
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/github.com/go-jose/go-jose/v4/opaque.go
  vendor/github.com/go-jose/go-jose/v4/shared.go
  vendor/github.com/go-jose/go-jose/v4/signing.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/golang.org/x/crypto/pkcs12/crypto.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#821 OCPBUGS-52505: golang.org/x/oauth2 v0.28.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/jws/jws.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#780 OSASINFRA-3657: Add support for storing OpenStack CA bundles
  README.md
  pkg/openstack/actuator.go
  pkg/openstack/utils.go
  pkg/operator/secretannotator/openstack/reconciler.go
Labels: approved, lgtm, jira/valid-reference

#825 OCPBUGS-51238: github.com/go-jose/go-jose/v4 v4.0.5
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v4/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/crypter.go
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/github.com/go-jose/go-jose/v4/opaque.go
  vendor/github.com/go-jose/go-jose/v4/shared.go
  vendor/github.com/go-jose/go-jose/v4/signing.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/golang.org/x/crypto/pkcs12/crypto.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#822 OCPBUGS-51550: Ignore SNYK-GOLANG-GOLANGORGXOAUTH2JWS-8749594 due to not being affected
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#826 OCPBUGS-52512: github.com/go-jose/go-jose/v4 v4.0.5
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v4/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/crypter.go
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/github.com/go-jose/go-jose/v4/opaque.go
  vendor/github.com/go-jose/go-jose/v4/shared.go
  vendor/github.com/go-jose/go-jose/v4/signing.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/golang.org/x/crypto/pkcs12/crypto.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#828 OCPBUGS-51548: Ignore SNYK-GOLANG-GOLANGORGXOAUTH2JWS-8749594 due to not being affected
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#827 NO-JIRA: Report the error when syncing STS secrets
  pkg/aws/actuator/actuator.go
  pkg/aws/actuator/actuator_test.go
Labels: approved, lgtm, jira/valid-reference

#829 OCPBUGS-51544: Ignore SNYK-GOLANG-GOLANGORGXOAUTH2JWS-8749594 due to not being affected
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#833 OCPBUGS-51540: Ignore SNYK-GOLANG-GOLANGORGXOAUTH2JWS-8749594 due to not being affected
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#830 OCPBUGS-51542: Ignore SNYK-GOLANG-GOLANGORGXOAUTH2JWS-8749594 due to not being affected
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#831 OCPBUGS-51546: Ignore SNYK-GOLANG-GOLANGORGXOAUTH2JWS-8749594 due to not being affected
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#836 OCPBUGS-53824: update github.com/golang-jwt/jwt
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#835 OCPBUGS-53345: github.com/golang/glog v1.2.4
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_nonwindows.go
  vendor/github.com/golang/glog/glog_file_windows.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
